# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('account_name', models.CharField(max_length=30)),
                ('account_phone', models.CharField(max_length=11)),
                ('api_hostname', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sKey', models.CharField(max_length=40, verbose_name='Secret Key')),
                ('iKey', models.CharField(max_length=20, unique=True, verbose_name='Integration Key')),
                ('name', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isc_auth.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifer', models.CharField(max_length=20)),
                ('is_activated', models.BooleanField(default=False)),
                ('dKey', models.CharField(max_length=256, null=True, verbose_name='Device Key')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isc_auth.Account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isc_auth.Account')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isc_auth.User'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('user_name', 'account')]),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('identifer', 'account')]),
        ),
    ]
