# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isc_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='seed',
            field=models.CharField(max_length=16, null=True, verbose_name='Random Seed'),
        ),
    ]
